spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crewdb
    username: postgres
    password: root-password-123
    hikari:
      schema: public

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false

telegram:
  bot:
    token: hui

jwt:
  secret: super-huinya
  access-token-ttl: 900000
  refresh-token-ttl: 2592000000
