spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crewdb
    username: postgres
    password: root-password-123
    hikari:
      schema: public

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false

telegram:
  bot:
    token: 8256676238:AAGmBF6jwHDKMLU5Rc8vG1NUPV9P3DplnSI

jwt:
  secret: F1r3!T0k3n#S3cUr3K3y_2025$SuperRandomBytes123
  access-token-ttl: 900000
  refresh-token-ttl: 2592000000
